lemrey/sdk-nrf

include/modem/nrf_modem_lib.h, lib/nrf_modem_lib/nrf_modem_lib.c
This FULL_DFU_MODE is where only DFU part of the modem library is
initialized and it uses all of the shared memory region.
Depends on https://github.com/NordicPlayground/libmodem/pull/14
=> Allow library to be initialized in Full DFU mode

include/modem/nrf_modem_lib.h, lib/nrf_modem_lib/Kconfig, lib/nrf_modem_lib/nrf_modem_os.c
Adds support for debugging memory.
Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>
=> lib: libmodem: add memory diagnostics

lib/nrf_modem_lib/nrf_modem_os.c
This commit adds support for error ECONNREFUSED.
Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>
=> lib: nrf_modem: add support for error ECONNREFUSED

lib/nrf_modem_lib/nrf91_sockets.c
Modem library has now a support for NRF_AF_UNSPEC address type
for DNS queries.
Signed-off-by: Seppo Takalo <seppo.takalo@nordicsemi.no>
=> Add support for NRF_AF_UNSPEC address type

lib/nrf_modem_lib/nrf91_sockets.c
This commit adds support in the offloading layer for the new
TCP server timeout socket option.
Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>
sdk-zephyr related PR: https://github.com/nrfconnect/sdk-zephyr/pull/527
=> lib: nrf_modem: add support for TCP server timeout

subsys/dfu/fmfu_fdev/src/fmfu_fdev.c, subsys/mgmt/fmfu/src/fmfu_mgmt.c
Update sdk-nrf to match new retvals from nrf_modem_lib
full_dfu interface (-NRF_ERRNOS instead of -1 on error).
=> subsys:nrf_modem_full_dfu: update retvals nrf_modem_lib

lib/nrf_modem_lib/nrf91_sockets.c
Remove deprecated API translations for PDN.
=> nrf_modem_lib: sockets: pdn: removal of deprecated

lib/nrf_modem_lib/nrf_modem_os.c, west.yml
This commit adds three new functions for logging:
* `nrf_modem_os_log_strdup` for transient logging
* `nrf_modem_os_log` for normal logging
* `nrf_modem_os_logump` for logging hexdump
Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>
=> lib: nrf_modem: add logging functions

lib/nrf_modem_lib/Kconfig, lib/nrf_modem_lib/nrf_modem_at_cmd_filter.c, subsys/dfu/fmfu_fdev/src/fmfu_fdev.c, subsys/mgmt/fmfu/src/fmfu_mgmt.c
Nitpicking for the libmodem release v1.4.0. 
Solving compliance issue with missing space after comma. 
@lemrey Don't know if you want to do it like this or rebase the original commits?
=> Nits: Release v1.4.0

doc/nrf/libraries/dfu/dfu_target.rst, doc/nrf/releases/release-notes-changelog.rst, lib/nrf_modem_lib/nrf91_sockets.c, subsys/dfu/dfu_target/src/dfu_target_modem_delta.c, west.yml
Remove deprecated API translations for socket dfu.
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>
_Commit: 9121b9c2e6272297e16c79a61c4b73a5ee1f3eb5 to be removed after [nrfconnect/sdk-nrf#6055](https://github.com/nrfconnect/sdk-nrf/pull/6055) is merged and included into lemrey/sdk-nrf_
=> nrf_modem_lib: removal of deprecated socket dfu

lib/nrf_modem_lib/nrf_modem_os.c
Modified nrf_modem_os_trace_put function to call the
nrf_modem_trace_processed_callback as soon as the uart tx or rtt tx
function returns.
Smoke testing of traces done using UART transport.
Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>
=> libmodem: Call the trace processed callback function after sending trace over uart/rtt

lib/nrf_modem_lib/nrf_modem_os.c
[NCSDK-12962](https://projecttools.nordicsemi.no/jira/browse/NCSDK-12962)
Use number of semaphores defined in nrf_modem_os.h to avoid mismatch
between library requirements and glue configuration.
=> lib: nrf_modem_lib: os: Use exported number of semaphores from modem lib

lib/nrf_modem_lib/nrf_modem_os.c
Implement nrf_modem_os_trace_irq_disable and
nrf_modem_os_trace_irq_disable functions in the glue layer.
Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>
=> lib: nrf_modem: Implement trace irq disable and enable functions

lib/nrf_modem_lib/Kconfig.modemlib, lib/nrf_modem_lib/nrf_modem_os.c
Add dedicated trace heap and functions nrf_modem can use
to allocate and free on it.
Add the same diagnostic functionality to trace heap as already
exist for library heap.
NCSDK-14230
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>
=> nrf_modem_lib: nrf_modem_os: add dedicated trace heap

applications/serial_lte_modem/src/slm_at_host.c, ext/curl/lib/url.h, lib/at_host/Kconfig
=> nrf: remove usage of `nrf_modem_limits.h` macros

lib/nrf_modem_lib/nrf_modem_os.c
Change nrf_modem_os_sem_take return value to -NRF_EAGAIN.
=> lib: nrf_modem_lib: change os_sem_take return value to -NRF_EAGAIN

lib/nrf_modem_lib/nrf_modem_os.c
When modem is not initialized.
=> lib: nrf_modem_lib: let `_timedwait()` return `-ESHUTDOWN`

include/modem/nrf_modem_lib.h, lib/nrf_modem_lib/nrf91_sockets.c, lib/nrf_modem_lib/nrf_modem_lib.c
Remove typedefs from modem library.
=> lib: nrf_modem_lib: cleanup typedefs

lib/nrf_modem_lib/Kconfig.modemlib, lib/nrf_modem_lib/nrf_modem_lib.c, lib/nrf_modem_lib/nrf_modem_os.c
Remove application IRQ (EGU1) from modem library.
=> lib: modem: Remove application IRQ

lib/nrf_modem_lib/nrf_modem_lib_trace.c, tests/lib/nrf_modem_lib/nrf_modem_lib_trace/src/main.c
Update nrf_modem_trace_get call to have the timeout in the input
parameters.
=> lib: nrf_modem: add timeout to trace_get

lib/nrf_modem_lib/nrf_modem_os.c
Add context to nrf_modem_os_event_notify and make use of it with nrf_modem_os_timedwait to select which threads to wake on events.
Co-authored-by: Fabian Nawratil <fabian.nawratil@nordicsemi.no>
=> lib: nrf_modem_lib: Add context to event_notify and use in timedwait

doc/nrf/libraries/dfu/fmfu_fdev.rst, doc/nrf/libraries/networking/nrf_cloud.rst, doc/nrf/releases/release-notes-1.7.0.rst, doc/nrf/releases/release-notes-1.8.0.rst, doc/nrf/ug_nrf91_features.rst, doc/nrfxlib/known-warnings.txt, include/mgmt/fmfu_mgmt.h, include/modem/nrf_modem_lib.h, lib/nrf_modem_lib/nrf_modem_lib.c, samples/nrf9160/fmfu_smp_svr/src/main.c, samples/nrf9160/http_update/full_modem_update/src/main.c, subsys/dfu/fmfu_fdev/src/fmfu_fdev.c, subsys/mgmt/fmfu/src/fmfu_mgmt.c, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_common.c, west.yml
Split the bootloader initialization from the normal library initialization. The bootloader mode requires the shared memory to be one larger chunk, compared to the normal mode, that split the shared memory in four.
=> lib: nrf_modem: split bootloader and normal library initialization

lib/nrf_modem_lib/nrf91_sockets.c
Remove `sin_len` and `sin6_len` fields, they are non-standard.
=> lib: nrf_modem: remove non-standard sockaddr fields

samples/cellular/gnss/src/main.c, samples/cellular/modem_shell/src/gnss/gnss.c
Fixed a couple of compilation issues with lesser used configurations, which were caused by the GNSS API changes merged recently.
=> gnss and modem_shell sample compilation fixes

lib/nrf_modem_lib/nrf91_sockets.c, tests/lib/nrf_modem_lib/nrf91_sockets/src/nrf91_sockets_test.c
When CONFIG_NET_SOCKETS_OFFLOAD_DISPATCHER is not enabled, the bindtodevice socket option should not be enabled.
=> lib: nrf_modem_lib: nrf91_sockets: fail bindtodevice w/o dispatcher

applications/asset_tracker_v2/src/main.c, applications/serial_lte_modem/src/main.c, applications/serial_lte_modem/src/slm_at_commands.c, applications/serial_lte_modem/src/slm_at_fota.c, applications/serial_lte_modem/src/slm_at_fota.h, include/modem/nrf_modem_lib.h, lib/bin/lwm2m_carrier/os/lwm2m_carrier.c, lib/lte_link_control/lte_lc_modem_hooks.c, lib/nrf_modem_lib/lte_connectivity/lte_connectivity.c, lib/nrf_modem_lib/lte_connectivity/lte_connectivity.h, lib/nrf_modem_lib/nrf_modem_lib.c, lib/nrf_modem_lib/nrf_modem_lib.ld, lib/nrf_modem_lib/nrf_modem_lib_trace.c, samples/cellular/azure_fota/src/main.c, samples/cellular/http_update/modem_delta_update/src/main.c, samples/cellular/modem_shell/src/fota/fota.c, samples/cellular/nrf_cloud_mqtt_multi_service/src/connection.c, samples/cellular/nrf_provisioning/sample.yaml, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_common.c, tests/lib/nrf_modem_lib/lte_connectivity/src/lte_connectivity_test.c, tests/subsys/net/lib/lwm2m_fota_utils/src/firmware.c, west.yml
It is no longer necessary to call nrf_modem_init twice when applying modem firmware updates.
=> lib: nrf_modem: init once on dfu apply

samples/cellular/modem_shell/src/gnss/gnss.c, samples/cellular/modem_shell/src/gnss/gnss.h, samples/cellular/modem_shell/src/gnss/gnss_shell.c
Added printing of GNSS PVT scheduled download flag. Added support for deleting the Extended Kalman Filter (EKF) state and deleting data using a custom bitmap.
=> samples: cellular: modem_shell: Add support for new GNSS API features

doc/nrf/libraries/modem/nrf_modem_lib/nrf_modem_lib_wrapper.rst, doc/nrf/libraries/modem/pdn.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/pdn/Kconfig, lib/pdn/pdn.c
Remove dependency on LTE LC library in the PDN library.
Depends on #128
=> lib: pdn: remove dependency on LTE link control library
